-- AYRES / Painel atual - Estrutura para o novo Supabase
-- Projeto: https://thafodnjbymtuczrykik.supabase.co
-- Rode este SQL no Supabase > SQL Editor.

create extension if not exists "pgcrypto";

-- Tabela principal usada pelo painel atual de estadias.
create table if not exists public.ldc_estadias (
  id bigint generated by default as identity primary key,
  local_id text not null unique,
  tipo text not null check (tipo in ('lancada', 'a_lancar')),
  filial text not null default 'jatai-go',
  placa text,
  status text,
  prioridade text default 'Normal',
  dados jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_ldc_estadias_filial on public.ldc_estadias(filial);
create index if not exists idx_ldc_estadias_tipo on public.ldc_estadias(tipo);
create index if not exists idx_ldc_estadias_status on public.ldc_estadias(status);
create index if not exists idx_ldc_estadias_updated_at on public.ldc_estadias(updated_at desc);

-- Usuários do painel atual.
create table if not exists public.ldc_usuarios (
  usuario text primary key,
  senha text not null,
  nome text not null,
  cargo text not null default 'Operador',
  avatar text,
  foto text,
  filial text not null default 'jatai-go',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Estrutura v2 já usada por captação/motoristas/transportadoras.
create table if not exists public.vl_filiais (
  id text primary key,
  nome text not null,
  cidade text,
  estado text,
  ativa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vl_profiles (
  usuario text primary key,
  nome text not null,
  cargo text not null default 'Operador',
  filial_id text references public.vl_filiais(id),
  avatar text,
  foto text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vl_motoristas (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  telefone text,
  telefone_limpo text unique,
  cidade text,
  observacao text,
  criado_por text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vl_transportadoras (
  id text primary key,
  nome text not null,
  ativa boolean not null default true,
  criado_por text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vl_captacoes (
  id uuid primary key default gen_random_uuid(),
  local_id text not null unique,
  motorista_id uuid references public.vl_motoristas(id) on delete set null,
  captador_usuario text,
  filial_id text references public.vl_filiais(id),
  operacao text not null default 'Farelo',
  status text not null default 'contatado',
  observacao text,
  quantidade_cargas integer not null default 1,
  data_captacao timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_vl_captacoes_filial on public.vl_captacoes(filial_id);
create index if not exists idx_vl_captacoes_captador on public.vl_captacoes(captador_usuario);
create index if not exists idx_vl_captacoes_status on public.vl_captacoes(status);

create table if not exists public.vl_motorista_carregamentos (
  id uuid primary key default gen_random_uuid(),
  motorista_id uuid references public.vl_motoristas(id) on delete cascade,
  captacao_id uuid unique references public.vl_captacoes(id) on delete cascade,
  filial_id text references public.vl_filiais(id),
  operacao text,
  captador_usuario text,
  observacao text,
  carregou_em timestamptz not null default now()
);

create table if not exists public.vl_captacao_eventos (
  id uuid primary key default gen_random_uuid(),
  captacao_id uuid references public.vl_captacoes(id) on delete cascade,
  status_anterior text,
  status_novo text,
  usuario text,
  observacao text,
  created_at timestamptz not null default now()
);

create or replace view public.vw_motoristas_que_carregam as
select
  m.id,
  m.nome,
  m.telefone,
  m.telefone_limpo,
  count(c.id)::int as carregamentos,
  max(c.carregou_em) as ultimo_carregamento
from public.vl_motoristas m
left join public.vl_motorista_carregamentos c on c.motorista_id = m.id
group by m.id, m.nome, m.telefone, m.telefone_limpo;

create or replace function public.delete_captacao_completa(p_local_id text)
returns boolean
language plpgsql
as $$
declare
  v_id uuid;
begin
  select id into v_id from public.vl_captacoes where local_id = p_local_id;
  if v_id is null then
    return true;
  end if;
  delete from public.vl_captacao_eventos where captacao_id = v_id;
  delete from public.vl_motorista_carregamentos where captacao_id = v_id;
  delete from public.vl_captacoes where id = v_id;
  return true;
end;
$$;

insert into public.vl_filiais (id, nome, cidade, estado)
values
  ('jatai-go', 'Jataí - GO', 'Jataí', 'GO'),
  ('mineiros-go', 'Mineiros - GO', 'Mineiros', 'GO')
on conflict (id) do nothing;

-- Usuários iniciais iguais aos defaults do front atual.
insert into public.ldc_usuarios (usuario, senha, nome, cargo, avatar, foto, filial)
values
  ('admin', '415ee99c86dc49b7c17810f40d4301897ceb5d8d4db7cbb6a677a4dd78885717', 'Administrador', 'Admin', 'AD', '', 'jatai-go'),
  ('jamis', '3171836572acf183cd88aebce7483bec28f7544d65439345c02702ab4b3e3705', 'Jamis', 'Operador', 'JA', '', 'jatai-go'),
  ('gleidson', '415ee99c86dc49b7c17810f40d4301897ceb5d8d4db7cbb6a677a4dd78885717', 'Gleidson', 'Operador', 'GL', '', 'jatai-go')
on conflict (usuario) do nothing;

insert into public.vl_profiles (usuario, nome, cargo, filial_id, avatar, foto)
values
  ('admin', 'Administrador', 'Admin', 'jatai-go', 'AD', ''),
  ('jamis', 'Jamis', 'Operador', 'jatai-go', 'JA', ''),
  ('gleidson', 'Gleidson', 'Operador', 'jatai-go', 'GL', '')
on conflict (usuario) do nothing;

-- Para o painel atual funcionar sem Supabase Auth nesta fase, RLS fica desligado.
-- Depois, na fase de segurança, ativamos RLS com Supabase Auth.
alter table public.ldc_estadias disable row level security;
alter table public.ldc_usuarios disable row level security;
alter table public.vl_filiais disable row level security;
alter table public.vl_profiles disable row level security;
alter table public.vl_motoristas disable row level security;
alter table public.vl_transportadoras disable row level security;
alter table public.vl_captacoes disable row level security;
alter table public.vl_motorista_carregamentos disable row level security;
alter table public.vl_captacao_eventos disable row level security;
